apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app: spot-termination-handler
resources:
  - cluster-role.yaml
  - service-account.yaml
  - clusterrole-binding.yaml
  - daemon-set.yaml
